apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  host: argocd-argocd.172.18.33.206.nip.io
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
